// Giyim ağırlıklı arama sorgusu listesi — birden fazla scrape adapter'ı (Amazon, Trendyol, ...)
// tarafından paylaşılır, böylece yeni bir site eklemek aynı kategori/sorgu setini otomatik kullanır.

import type { CategoryQuery } from "./types";

export const CATEGORIES: CategoryQuery[] = [
  { query: "erkek tişört", category: "Tişört", take: 40 },
  { query: "kadın tişört", category: "Tişört", take: 40 },
  { query: "kadın elbise", category: "Elbise", take: 40 },
  { query: "erkek ceket", category: "Ceket", take: 40 },
  { query: "kadın ceket", category: "Ceket", take: 40 },
  { query: "kadın pantolon", category: "Pantolon", take: 40 },
  { query: "erkek pantolon", category: "Pantolon", take: 40 },
  { query: "spor ayakkabı", category: "Ayakkabı", take: 40 },
  { query: "kadın ayakkabı", category: "Ayakkabı", take: 40 },
  { query: "erkek ayakkabı", category: "Ayakkabı", take: 40 },
  { query: "kadın kazak", category: "Kazak", take: 40 },
  { query: "erkek kazak", category: "Kazak", take: 40 },
  { query: "erkek gömlek", category: "Gömlek", take: 40 },
  { query: "kadın gömlek", category: "Gömlek", take: 40 },
  { query: "kadın çanta", category: "Aksesuar", take: 40 },
  { query: "erkek şort", category: "Şort", take: 40 },
  { query: "kadın etek", category: "Etek", take: 40 },
  { query: "kadın mont", category: "Mont", take: 40 },
  { query: "erkek mont", category: "Mont", take: 40 },
  { query: "kadın bluz", category: "Bluz", take: 40 },
  { query: "erkek eşofman", category: "Eşofman", take: 40 },
  { query: "kadın tayt", category: "Tayt", take: 40 },
  { query: "kadın çorap", category: "Çorap", take: 40 },
  { query: "erkek şapka", category: "Aksesuar", take: 40 },
  { query: "kadın hırka", category: "Hırka", take: 40 },
  { query: "erkek hırka", category: "Hırka", take: 40 },
  { query: "kadın yelek", category: "Yelek", take: 40 },
  { query: "erkek yelek", category: "Yelek", take: 40 },
  { query: "kadın trençkot", category: "Mont", take: 40 },
  { query: "erkek kaban", category: "Mont", take: 40 },
  { query: "erkek kot ceket", category: "Ceket", take: 40 },
  { query: "kadın kot ceket", category: "Ceket", take: 40 },
  { query: "erkek kot pantolon", category: "Pantolon", take: 40 },
  { query: "kadın kot pantolon", category: "Pantolon", take: 40 },
  { query: "kadın triko kazak", category: "Kazak", take: 40 },
  { query: "erkek triko kazak", category: "Kazak", take: 40 },
  { query: "büyük beden tişört", category: "Tişört", take: 40 },
  { query: "büyük beden elbise", category: "Elbise", take: 40 },
  { query: "erkek spor tişört", category: "Tişört", take: 40 },
  { query: "kadın spor tişört", category: "Tişört", take: 40 },
  { query: "kadın gece elbisesi", category: "Elbise", take: 40 },
  { query: "erkek takım elbise", category: "Takım Elbise", take: 40 },
  { query: "kadın jile", category: "Yelek", take: 40 },
  { query: "erkek sweatshirt", category: "Eşofman", take: 40 },
  { query: "kadın sweatshirt", category: "Eşofman", take: 40 },
  { query: "erkek kapüşonlu", category: "Eşofman", take: 40 },
  { query: "kadın kapüşonlu", category: "Eşofman", take: 40 },
];
